sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
- '6'
before_script:
- npm prune
before_install: scripts/travis/before.sh
after_success: scripts/travis/after_success.sh
script: npm run lint && npm test
git:
  depth: 1
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
